/**
 * Data Layer — Supabase implementation
 *
 * This is the canonical data access module for the Saudidex project.
 * All data access in hooks/pages should use these helpers.
 *
 * API surface is maintained for compatibility while using Supabase.
 */

import { supabase, supabaseAdmin } from './supabase';
import { validator } from './validator';
import type { ScrapedPageResult } from '@/engine/core/scraper';

export interface StoredSourcePageRow {
  id: string;
  url: string;
  canonical_url?: string | null;
}

export interface SourcePageEvidenceRef {
  id?: string | null;
  url: string;
  canonical_url?: string | null;
  html?: string | null;
  text_content?: string | null;
  content?: string | null;
  page_type?: string | null;
}

export type DataLayer = 'supabase';
export const DATA_LAYER: DataLayer = 'supabase';

// Operator map from Firestore syntax to Supabase PostgREST filter methods
const OP_MAP: Record<string, string> = {
  '==': 'eq',
  '!=': 'neq',
  '>': 'gt',
  '>=': 'gte',
  '<': 'lt',
  '<=': 'lte',
  'in': 'in',
  'not-in': 'not.in',
  'array-contains': 'cs',     // JSONB contains
  'array-contains-any': 'ov', // JSONB overlaps
};

function client() {
  // Prefer admin (server) key when available, fall back to anon (browser)
  return supabaseAdmin ?? supabase;
}

function requireClient() {
  const c = client();
  if (!c) throw new Error('[DataLayer] Supabase not configured.');
  return c;
}

/** AI/extractor legacy keys — not columns on public.companies */
function sanitizeCompanyPayload<T extends Record<string, unknown>>(data: T): T {
  return validator.sanitizeCompanyPersistencePayload(data);
}

// ============================================================
// Core CRUD
// ============================================================

/** Fetch a single row by id */
async function getDoc<T>(table: string, id: string): Promise<T | null> {
  const { data, error } = await requireClient()
    .from(table)
    .select('*')
    .eq('id', id)
    .maybeSingle();
  if (error) throw error;
  return data as T | null;
}

/** Query rows with optional filters, ordering, and limit */
async function queryDocs<T>(
  table: string,
  filters: Array<{ field: string; op: string; value: unknown }> = [],
  options?: { orderBy?: { field: string; direction?: 'asc' | 'desc' }; limit?: number }
): Promise<T[]> {
  let q = requireClient().from(table).select('*');

  for (const f of filters) {
    const method = OP_MAP[f.op] ?? 'eq';
    q = (q as any)[method](f.field, f.value);
  }

  if (options?.orderBy) {
    q = q.order(options.orderBy.field, { ascending: options.orderBy.direction !== 'desc' });
  }
  if (options?.limit) {
    q = q.limit(options.limit);
  }

  const { data, error } = await q;
  if (error) throw error;
  return (data ?? []) as T[];
}

/** Upsert (insert or update) a row */
async function setDoc(table: string, id: string, data: Record<string, unknown>): Promise<void> {
  const row = table === 'companies' ? sanitizeCompanyPayload({ ...data, id }) : { ...data, id };
  const { error } = await requireClient()
    .from(table)
    .upsert(row, { onConflict: 'id' });
  if (error) throw error;
}

/** Update specific fields on a row */
async function updateDoc(table: string, id: string, data: Record<string, unknown>): Promise<void> {
  const payload = table === 'companies' ? sanitizeCompanyPayload({ ...data }) : data;
  const { error } = await requireClient()
    .from(table)
    .update(payload)
    .eq('id', id);
  if (error) throw error;
}

/** Delete a row */
async function deleteDoc(table: string, id: string): Promise<void> {
  const { error } = await requireClient().from(table).delete().eq('id', id);
  if (error) throw error;
}

/** Insert a new row (no id required — auto-generated by DB if not supplied) */
async function addDoc(table: string, data: Record<string, unknown>): Promise<{ id: string }> {
  const payload = table === 'companies' ? sanitizeCompanyPayload({ ...data }) : data;
  const { data: inserted, error } = await requireClient()
    .from(table)
    .insert(payload)
    .select('id')
    .single();
  if (error) throw error;
  return inserted as { id: string };
}

// ============================================================
// Batch helpers (Supabase doesn't have a Firestore-style batch,
// but we can run multiple upserts/updates in a single RPC or
// use Promise.all for independent writes)
// ============================================================

/** Batch update multiple rows in the same table */
async function batchUpdate(
  table: string,
  updates: Array<{ id: string; data: Record<string, unknown> }>
): Promise<void> {
  await Promise.all(updates.map(({ id, data }) => updateDoc(table, id, data)));
}

/** Batch delete multiple rows in the same table */
async function batchDelete(table: string, ids: string[]): Promise<void> {
  const { error } = await requireClient().from(table).delete().in('id', ids);
  if (error) throw error;
}

// ============================================================
// Real-time subscriptions (replaces Firestore onSnapshot)
// ============================================================

/**
 * Subscribe to real-time changes on a table.
 * Returns an unsubscribe function.
 */
function onSnapshot<T>(
  table: string,
  filters: Array<{ field: string; op: string; value: unknown }>,
  callback: (docs: T[]) => void,
  onError?: (error: Error) => void
): () => void {
  const c = requireClient();

  // Initial fetch
  queryDocs<T>(table, filters)
    .then(callback)
    .catch(err => onError?.(err as Error));

  const channel = c
    .channel(`realtime:${table}:${Date.now()}`)
    .on(
      'postgres_changes',
      { event: '*', schema: 'public', table },
      () => {
        queryDocs<T>(table, filters)
          .then(callback)
          .catch(err => onError?.(err as Error));
      }
    )
    .subscribe();

  return () => {
    c.removeChannel(channel);
  };
}

// ============================================================
// ID counter (replaces Firestore runTransaction on metadata doc)
// ============================================================

/** Get next auto-incremented company ID via Postgres function */
async function getNextCompanyId(): Promise<number> {
  const { data, error } = await requireClient().rpc('get_next_company_id');
  if (error) throw error;
  return data as number;
}

/** Reserve `count` sequential company IDs; returns the first one */
async function getNextCompanyIds(count: number): Promise<number[]> {
  const { data, error } = await requireClient().rpc('get_next_company_ids', { count });
  if (error) throw error;
  const startId = data as number;
  return Array.from({ length: count }, (_, i) => startId + i);
}

// ============================================================
// Specialized Storage Helpers
// ============================================================

/** Store field confidence and source evidence */

/** Store field confidence and source evidence */
function normalizeEvidenceContent(value: unknown): string {
  if (value == null) return '';
  if (typeof value === 'string') return value.toLowerCase();
  try {
    return JSON.stringify(value).toLowerCase();
  } catch {
    return String(value).toLowerCase();
  }
}

function chooseEvidencePage(
  fieldName: string,
  evidence: unknown,
  value: unknown,
  sourcePages: SourcePageEvidenceRef[],
): SourcePageEvidenceRef | null {
  if (sourcePages.length === 0) return null;

  const evidenceText = normalizeEvidenceContent(evidence).trim();
  const valueText = normalizeEvidenceContent(value).trim();

  if (evidenceText) {
    const exactEvidenceMatch = sourcePages.find((page) => {
      const pageText = `${page.html || ''}\n${page.text_content || page.content || ''}`.toLowerCase();
      return pageText.includes(evidenceText);
    });
    if (exactEvidenceMatch) return exactEvidenceMatch;
  }

  if (valueText && valueText.length >= 4) {
    const valueMatch = sourcePages.find((page) => {
      const pageText = `${page.html || ''}\n${page.text_content || page.content || ''}`.toLowerCase();
      return pageText.includes(valueText);
    });
    if (valueMatch) return valueMatch;
  }

  const preferredPageType = (() => {
    if (['email', 'sales_email', 'procurement_email', 'phone', 'whatsapp', 'contact_email', 'full_address'].includes(fieldName)) {
      return 'contact';
    }
    if (['description_en', 'description_ar', 'name_en', 'name_ar'].includes(fieldName)) {
      return 'about';
    }
    if (['products', 'services', 'categories', 'fields'].includes(fieldName)) {
      return 'products';
    }
    return null;
  })();

  if (preferredPageType) {
    const typedPage = sourcePages.find((page) => page.page_type === preferredPageType);
    if (typedPage) return typedPage;
  }

  return sourcePages[0];
}

async function storeFieldEvidence(companyId: string, data: any, sourcePages: SourcePageEvidenceRef[]): Promise<void> {
  const c = requireClient();
  if (!data.field_confidence) return;

  const sanitizedFieldConfidence = validator.sanitizeConfidenceMap(
    data.field_confidence,
    'field_confidence'
  );

  const entries = Object.entries(sanitizedFieldConfidence).map(([field, score]) => {
    // Priority: 1. AI provided snippet, 2. Field value slice, 3. null
    const evidence = (data.field_evidence?.[field]) || (data[field] ? String(data[field]).slice(0, 500) : null);
    const matchedPage = chooseEvidencePage(field, data.field_evidence?.[field], data[field], sourcePages);
    
    return {
      company_id: companyId,
      field_name: field,
      confidence: score,
      source_url: matchedPage?.url || null,
      source_page_id: matchedPage?.id || null,
      extraction_method: 'ai_suggestion',
      extraction_detail: evidence,
      value: data[field] || null,
      is_locked: score >= 0.9
    };
  });

  if (entries.length > 0) {
    const { error } = await c.from('field_evidence').upsert(entries, { onConflict: 'company_id,field_name' });
    if (error) console.warn("[DataLayer] Failed to store field evidence:", error.message);
  }
}

/** Store raw HTML for a company (scraped pages) */
async function storeRawHtml(companyId: string, pages: Array<{ url: string; html: string; page_type: string }>): Promise<void> {
  const c = requireClient();
  if (pages.length === 0) return;

  const payload = {
    company_id: companyId,
    pages: pages.map((p, i) => ({
      ...p,
      scraped_at: new Date().toISOString(),
      order: i
    })),
    stored_at: new Date().toISOString()
  };

  const { error } = await c.from('company_raw_html').upsert(payload, { onConflict: 'company_id' });
  if (error) console.warn("[DataLayer] Failed to store raw HTML:", error.message);
}

function tryGetDomain(url?: string | null): string | null {
  if (!url) return null;
  try {
    return new URL(url).hostname.toLowerCase();
  } catch {
    return null;
  }
}

async function ensureScrapeSource(baseUrl: string, name?: string, type: string = 'website'): Promise<string | null> {
  const c = requireClient();
  const normalizedName = name || tryGetDomain(baseUrl) || baseUrl;

  const { data, error } = await c
    .from('scrape_sources')
    .upsert({
      base_url: baseUrl,
      name: normalizedName,
      type,
      is_active: true,
    }, { onConflict: 'base_url' })
    .select('id')
    .single();

  if (error) {
    console.warn('[DataLayer] Failed to ensure scrape source:', error.message);
    return null;
  }

  return data?.id ?? null;
}

async function createScrapeRun(sourceId: string | null): Promise<string | null> {
  const c = requireClient();
  const { data, error } = await c
    .from('scrape_runs')
    .insert({ source_id: sourceId, status: 'running' })
    .select('id')
    .single();

  if (error) {
    console.warn('[DataLayer] Failed to create scrape run:', error.message);
    return null;
  }

  return data?.id ?? null;
}

async function finalizeScrapeRun(
  runId: string | null,
  updates: {
    status: string;
    total_pages?: number;
    total_success?: number;
    total_failed?: number;
    error_message?: string | null;
  }
): Promise<void> {
  if (!runId) return;
  const c = requireClient();

  const { error } = await c
    .from('scrape_runs')
    .update({
      ...updates,
      finished_at: new Date().toISOString(),
    })
    .eq('id', runId);

  if (error) {
    console.warn('[DataLayer] Failed to finalize scrape run:', error.message);
  }
}

async function logScrapeError(input: {
  runId?: string | null;
  sourceUrl: string;
  errorType: string;
  errorMessage: string;
  htmlSnapshot?: string | null;
  screenshotUrl?: string | null;
}): Promise<void> {
  const c = requireClient();
  const { error } = await c.from('scrape_errors').insert({
    run_id: input.runId || null,
    source_url: input.sourceUrl,
    error_type: input.errorType,
    error_message: input.errorMessage,
    html_snapshot: input.htmlSnapshot || null,
    screenshot_url: input.screenshotUrl || null,
  });

  if (error) {
    console.warn('[DataLayer] Failed to log scrape error:', error.message);
  }
}

async function storeSourcePages(
  pages: ScrapedPageResult[],
  options?: { crawlJobId?: string | null; seedId?: string | null; defaultStatus?: 'raw' | 'parsed' | 'error' }
): Promise<StoredSourcePageRow[]> {
  const c = requireClient();
  if (pages.length === 0) return [];

  const rows = pages.map(page => ({
    url: page.url,
    canonical_url: page.url,
    domain: tryGetDomain(page.url),
    page_type: page.page_type || 'other',
    html: page.html,
    text_content: page.content,
    title: null,
    status: options?.defaultStatus || 'raw',
    crawl_job_id: options?.crawlJobId || null,
    seed_id: options?.seedId || null,
    response_code: page.response_code || null,
    response_headers: page.response_headers || null,
    fetch_method: page.fetch_method || null,
    fetch_time_ms: null,
    html_size_bytes: page.html?.length || 0,
    crawled_at: new Date().toISOString(),
  }));

  const { data, error } = await c
    .from('source_pages')
    .insert(rows)
    .select('id, url, canonical_url');
  if (error) {
    console.warn('[DataLayer] Failed to store source pages:', error.message);
    return [];
  }

  return (data || []) as StoredSourcePageRow[];
}

async function syncCompanyContacts(companyId: string, data: Record<string, unknown>, sourceUrl?: string | null): Promise<void> {
  const c = requireClient();
  const desired = [
    { contact_type: 'general', email: data.email, phone: data.phone, whatsapp: data.whatsapp },
    { contact_type: 'general', email: data.contact_email, phone: null, whatsapp: null },
    { contact_type: 'sales', email: data.sales_email, phone: null, whatsapp: null },
    { contact_type: 'procurement', email: data.procurement_email, phone: null, whatsapp: null },
  ]
    .filter(entry => entry.email || entry.phone || entry.whatsapp)
    .map(entry => ({
      company_id: companyId,
      contact_type: entry.contact_type,
      email: typeof entry.email === 'string' ? entry.email : null,
      phone: typeof entry.phone === 'string' ? entry.phone : null,
      whatsapp: typeof entry.whatsapp === 'string' ? entry.whatsapp : null,
      source_url: sourceUrl || null,
      verified: false,
    }));

  if (desired.length === 0) return;

  const { data: existing, error: fetchError } = await c
    .from('company_contacts')
    .select('contact_type, email, phone, whatsapp')
    .eq('company_id', companyId);

  if (fetchError) {
    console.warn('[DataLayer] Failed to read company contacts:', fetchError.message);
    return;
  }

  const existingKeys = new Set((existing || []).map(row => [
    row.contact_type || '',
    row.email || '',
    row.phone || '',
    row.whatsapp || '',
  ].join('|')));

  const toInsert = desired.filter(row => !existingKeys.has([
    row.contact_type || '',
    row.email || '',
    row.phone || '',
    row.whatsapp || '',
  ].join('|')));

  if (toInsert.length === 0) return;

  const { error } = await c.from('company_contacts').insert(toInsert);
  if (error) {
    console.warn('[DataLayer] Failed to sync company contacts:', error.message);
  }
}

// ============================================================
// Exported data layer object
// ============================================================

export const dataLayer = {
  getDoc,
  query: queryDocs,
  setDoc,
  updateDoc,
  deleteDoc,
  addDoc,
  batchUpdate,
  batchDelete,
  onSnapshot,
  getNextCompanyId,
  getNextCompanyIds,
  storeFieldEvidence,
  storeRawHtml,
  ensureScrapeSource,
  createScrapeRun,
  finalizeScrapeRun,
  logScrapeError,
  storeSourcePages,
  syncCompanyContacts,
  serverTimestamp: () => new Date().toISOString(),
};

// Named exports for direct import by call-sites
export {
  getDoc,
  queryDocs,
  setDoc,
  updateDoc,
  deleteDoc,
  addDoc,
  batchUpdate,
  batchDelete,
  onSnapshot,
  getNextCompanyId,
  getNextCompanyIds,
  storeFieldEvidence,
  storeRawHtml,
  ensureScrapeSource,
  createScrapeRun,
  finalizeScrapeRun,
  logScrapeError,
  storeSourcePages,
  syncCompanyContacts
};

console.log('[DataLayer] Using: supabase');
